Repository BlueCodeSystems/smartcerv, pull requests merged in 2019-10, with the labels that each got.

#260 changed Registered clients to Total clients enrolled and increased st…
  cervicalcancer/src/main/java/zm/gov/moh/cervicalcancer/submodule/cervicalcancer/view/CervicalCancerActivity.java
  cervicalcancer/src/main/res/layout/cervical_cancer_activity.xml
  core/src/main/java/zm/gov/moh/core/repository/database/dao/domain/PatientDao.java
Labels: Ready for QA

#263 Resolved:If VIA negative result is selected,entire section concerning lesion is inactive
  cervicalcancer/src/main/assets/forms/via_test_results.json
Labels: v1.0.0-alpha.7

#266 changed label from Enroll patient to Enroll Client on cervical Cancer…
  cervicalcancer/src/main/res/layout/cervical_cancer_activity.xml
Labels: Has PR, Ready for QA

#272 Issue#251
  cervicalcancer/src/main/java/zm/gov/moh/cervicalcancer/submodule/cervicalcancer/view/CervicalCancerActivity.java
  cervicalcancer/src/main/java/zm/gov/moh/cervicalcancer/submodule/cervicalcancer/viewmodel/CervicalCancerViewModel.java
  cervicalcancer/src/main/res/drawable/optionbackground.xml
  cervicalcancer/src/main/res/layout/cervical_cancer_activity.xml
  core/src/main/java/zm/gov/moh/core/repository/database/dao/domain/PatientDao.java
Labels: Has PR, Ready for QA

#273 removed logout button from toolbar and implemented close feature when…
  common/src/main/java/zm/gov/moh/common/base/BaseActivity.java
  common/src/main/res/layout/base_toolbar.xml
Labels: Has PR, Ready for QA

#277 Added error reporting functionality using Crashlytics SDK. using fabric only for the time being,firebase integration to be added in future releases.
  app/build.gradle
  app/fabric.properties
  app/src/main/AndroidManifest.xml
  app/src/main/java/zm/gov/moh/app/ApplicationContext.java
  cervicalcancer/src/main/java/zm/gov/moh/cervicalcancer/submodule/dashboard/patient/view/PatientDashboardActivity.java
  cervicalcancer/src/main/res/layout/activity_patient_dashboard.xml
Labels: Needs Review
